name: Publish

on:
  workflow_run:
    workflows: ["Build"]
    branches:
      - master
      - feature/*
    types:
      - completed

jobs:
  publish:
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}

    - name: Restore NuGet Packages
      run: dotnet restore src/EncompassRest/EncompassRest.csproj

    - name: Build Solution
      run: dotnet build -c $env:CONFIGURATION src/EncompassRest/EncompassRest.csproj

    - name: Push NuGet Package
      run: dotnet nuget push --no-symbols --skip-duplicates src/EncompassRest/bin/Release/*.nupkg
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
